services:
  frontend:
    ports:
      - "443:443"
    volumes:
      - ./frontend/nginx.prod.conf:/etc/nginx/conf.d/default.conf
      - nginx-certs:/etc/letsencrypt

  certbot:
    image: certbot/certbot
    volumes:
      - nginx-certs:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./frontend:/var/www/html
    command: >-
      certonly --webroot
      --webroot-path=/var/www/html
      --email lcambon@fi.uba.ar  
      --agree-tos
      --no-eff-email
      -d crypto-masivos.lat

volumes:
  nginx-certs:
  certbot-var: