
x-db-environment: &db-env
  POSTGRES_DB: ${POSTGRES_DB}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_HOST: ${POSTGRES_HOST}
  POSTGRES_PORT: ${POSTGRES_PORT}
services:
  db:
    container_name: crypto-masivos-db
    image: postgres:latest
    environment:
      <<: *db-env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: crypto_masivos_backend:latest
    environment:
      <<: *db-env
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db_data:
