version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/nginx.prod.conf:/etc/nginx/conf.d/default.conf
      - certbot-etc:/etc/letsencrypt
      - certbot-www:/var/www/html
    ports:
      - "80:80"
      - "443:443"

  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-www:/usr/share/nginx/html
    entrypoint: certbot
    command: >
      certonly --webroot --webroot-path=/usr/share/nginx/html
      --email tu_email@dominio.com
      --agree-tos
      --no-eff-email
      -d crypto-masivos.lat

volumes:
  certbot-etc:
  certbot-www: