services:
  db:
    container_name: crypto-masivos-db
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: crypto_masivos_backend:latest
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db_data:
