
x-db-environment: &db-env
  POSTGRES_DB: ${POSTGRES_DB}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_HOST: ${POSTGRES_HOST}
  POSTGRES_PORT: ${POSTGRES_PORT}
services:
  db:
    container_name: crypto-masivos-db
    image: postgres:latest
    environment:
      <<: *db-env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/init_data.sql:/docker-entrypoint-initdb.d/init_data.sql
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: crypto_masivos_backend:latest
    environment:
      <<: *db-env
      JWT_SECRET: ${JWT_SECRET}
      CORS_ORIGIN: ${CORS_ORIGIN}
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: crypto_masivos_frontend:latest
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  db_data:
